### ISSUE TITLE
Need informations 

### ISSUE THREAD

**Issue by ghost** [getreu/asn1-tiny-decoder#1]
I need some more informations about your library specially about what do you mean, on your blog "http://www.getreu.net/public/downloads/software/ASN1_decoder/README.html", with: " Furthermore Pyasn1 is not designed to parse large files " & " asn1tinydecoder.py is a simple and fast ASN.1 decoder without external libraries designed to parse large files. "

my problem is as follows:

i have a large ASN1 file called "a32298-b60.asn" it is made of 1704 rows and through it i need to decode a CDR ( Charging Data Record ) file...

If possible i want to know if your module is what i am looking for...
if you need more informations e-mail me :)

**Comment by getreu** [comment]
`asn1-tiny-decoder` can browse through much bigger data sets than yours. It is so fast because it does not de-serialize.  Scanning through the  [testdata](https://github.com/getreu/asn1-tiny-decoder/blob/master/www.sk.ee-esteid2011.crl) with 19MB takes some seconds only.

If you need to find something in your data or you want to index your data with a dictionary then `asn1-tiny-decoder` is a good choice. Alternatively if you need to de-serialize all your 1704 objects you may prefer [pyasn1](https://pypi.python.org/pypi/pyasn1).

**Comment by ghost** [comment]
can you explain me how do your library works plz?
i didn't understand it so good

**Comment by cifvts** [comment]
@getreu The situation here is this one: we need to build a software to decode a BER encoded buffer. This blob is made by some systems and we have the ASN.1 definition of it, which is the file mentioned earlier. These BER encoded buffer can come from various source, might be produced differently and we don't know in advance which fields are in or not.
Given that we have the ASN.1 Schema, the question is: how can we use you library it to read what is inside the the buffer? From what I understood of your example, you do a raw read of your test file but you know the structure of it and assume it doesn't change, am I correct?

What we are looking for, and might not be this tool, is something that parse our ASN.1 schema and create structs and helper function to access the BER buffer to get data from inside (or if not present, manage it).

**Comment by getreu** [comment]
> These BER encoded buffer can come from various source, might be produced differently and we don't know in advance which fields are in or not.

What you want is a processor: `ASN1 data structure definition + data -> output`? (like XML procssing.)
All ASN1 decoder I have seen need the exact definition of the data structure at compile time. So this one. It seems this is not the right tool for you, sorry.

**Comment by cifvts** [comment]
Thanks for your clarification, really appreciate

**Comment by getreu** [comment]
@cifvts: I read through your question again.

> These BER encoded buffer can come from various source, might be produced differently and we don't know in advance which fields are in or not.

Actually `asn1-tiny-decoder` is just a tiny little tool to help to browse through your data. Although I have not used it in the way you describe, it should be easy to adapt to deal with some unknown fields.
