### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Fethbita** [getreu/asn1-tiny-decoder#4]
Is it possible to add a LICENSE to this project?

**Comment by getreu** [comment]
Yes, see 2fca92e6b721e19033de9977d05bff0378c305eb

**Comment by getreu** [comment]
Is this Ok for you?

**Comment by Fethbita** [comment]
Yes this is fine. First time I see a dual license used in a project (I prefer to use MIT license). I agree with my contributions to be licensed as such (dual licensed) as well. Thank you.
