### ISSUE TITLE
asn1_node_is_child_of not terminating

### ISSUE THREAD

**Issue by dirkx** [getreu/asn1-tiny-decoder#5]
I've got a fairly trival bit of code that parses set of sequences with a small header (actual format and example attached).

I had expected below ```asn1_node_is_child_of``` to terminate on the last item of the set (of sequences).

```
#!env python
from asn1tinydecoder import asn1_node_root, asn1_get_all, asn1_get_value, \
                        asn1_get_value_of_type, asn1_node_next, asn1_node_first_child, \
                        asn1_read_length, asn1_node_is_child_of

import sys
der = sys.stdin.buffer.read()
root = asn1_node_root(der)
hdr = asn1_node_first_child(der,root)
[icao-ml-spec.asn1.txt](https://github.com/getreu/asn1-tiny-decoder/files/6254519/icao-ml-spec.asn1.txt)

list = asn1_node_next(der,hdr)
item = asn1_node_first_child(der,list)

while asn1_node_is_child_of(list, item):
        with open('cert-{:05d}.der'.format(k),'wb') as f:
                f.write(asn1_get_all(der,item))
        item = asn1_node_next(der,item)
```
bit it seems to run one over. So I guess I am misunderstanding how is_child_off works (I worked around it for now by changing in 

```
def asn1_node_is_child_of(i_indices, j_indices):
    ... snipped ...
   #  return ((ixf <= jxs) and (jxl <= ixl)) or ((jxf <= ixs) and (ixl <= jxl))
    return ((ixf <= jxs) and (jxl < ixl)) or ((jxf <= ixs) and (ixl < jxl))
```

But that surely is the wrong way ? 

Thanks,

Dw. (filetypes mangled a bit to work around the github upload limit)

[icao-ml-spec.asn1.txt](https://github.com/getreu/asn1-tiny-decoder/files/6254521/icao-ml-spec.asn1.txt)
[input.zip](https://github.com/getreu/asn1-tiny-decoder/files/6254514/input.zip)

**Comment by getreu** [comment]
`def asn1_node_is_child_of` is true when `i` is completely inside `j`, or, `j` is completely inside `i`. They should not overlap, but the `ixl` and `jxl` are allowed to point to the same byte. The original test `return ((ixf <= jxs) and (jxl <= ixl)) or ((jxf <= ixs) and (ixl <= jxl))` seems correct to me. I guess there is a problem with you loop. Please compare your loop to the example given in `../data/search_serial_in_large_CRL.py`.

**Comment by Fethbita** [comment]
@dirkx maybe something like this might solve your problem?
``` python
list = asn1_node_next(der,hdr)
item = asn1_node_first_child(der,list)
last_byte = list[2]
while True:
    # do something
    if item[2] == last_byte:
        break
    item = asn1_node_next(der,item)
```
